apiVersion: v1
kind: Service
metadata:
    name: "abakskubenet-70e1"
    labels:
        app: "abakskubenet-70e1"
spec:
    type: LoadBalancer
    ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
    selector:
        app: "abakskubenet-70e1"