on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: abakskubenet.azurecr.io
        username: ${{ secrets.acr_abakskubenet_username }}
        password: ${{ secrets.acr_abakskubenet_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/2.4/debian-10" -f  "2.4/debian-10/Dockerfile" -t abakskubenet.azurecr.io/abakskubenet:${{ github.sha }} --label dockerfile-path=2.4/debian-10/Dockerfile
        docker push abakskubenet.azurecr.io/abakskubenet:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_abakskubenet_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep abakskubenet3589 | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace abakskubenet3589`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: abakskubenet3589
        container-registry-url: abakskubenet.azurecr.io
        container-registry-username: ${{ secrets.acr_abakskubenet_username }}
        container-registry-password: ${{ secrets.acr_abakskubenet_password }}
        secret-name: abakskubenetdockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: abakskubenet3589
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
        images: |
          abakskubenet.azurecr.io/abakskubenet:${{ github.sha }}
        imagepullsecrets: |
          abakskubenetdockerauth
